# Job Sources Configuration
#
# Categorizes sources by how Claude can access them:
# - api: Direct API calls, reliable, structured data
# - search: WebSearch discovery, follow links, partial success
# - manual: User must browse, export, or forward to Claude
#
# For manual sources, Claude can still analyze/process data
# once the user provides it.

schema_version: 2

# ============================================================
# RSS SOURCES - Structured feeds, reliable, bypasses bot detection
# ============================================================
rss:

  weworkremotely:
    name: We Work Remotely
    type: rss
    reliability: high
    feeds:
      all: "https://weworkremotely.com/remote-jobs.rss"
      programming: "https://weworkremotely.com/categories/remote-programming-jobs.rss"
      devops: "https://weworkremotely.com/categories/remote-devops-sysadmin-jobs.rss"
      design: "https://weworkremotely.com/categories/remote-design-jobs.rss"
      product: "https://weworkremotely.com/categories/remote-product-jobs.rss"
      management: "https://weworkremotely.com/categories/remote-management-jobs.rss"
    recommended_feeds:
      - programming
      - devops
      - product
    parse:
      item_element: item
      fields:
        title: title
        link: link
        description: description
        pub_date: pubDate
        category: category
        region: region
        type: type  # Full-Time, Contract, etc.
    notes: |
      RSS bypasses the 403 on the website.
      Use category feeds to reduce noise.
      pubDate is RFC 822 format.
    rate_limit: respectful (1 req/min per feed)

  remoterocketship:
    name: Remote Rocketship
    type: rss
    reliability: unknown
    feeds:
      all: "https://www.remoterocketship.com/feed"
    notes: |
      Test if RSS exists and works.
      Fallback to search if blocked.
    status: untested

# ============================================================
# CURATED SOURCES - GitHub lists, community-maintained
# ============================================================
#
# IMPORTANT: Randomization Strategy
# ----------------------------------
# Long lists have alphabetical/recognition bias. To ensure fair coverage:
#
# 1. SHUFFLE before scanning:
#    ```python
#    import random
#    random.seed(int(date.today().strftime("%Y%m%d")))  # Reproducible per day
#    random.shuffle(companies)
#    ```
#
# 2. TRACK scanned companies in state file:
#    /tmp/curated-scan-state.yaml:
#      hiring_without_whiteboards:
#        last_scanned: 2026-01-13
#        offset: 150  # Resume from here next week
#        recently_checked: [company1, company2, ...]
#
# 3. ROTATE through list over multiple weeks:
#    - Week 1: companies[0:100]
#    - Week 2: companies[100:200]
#    - Week 3: companies[200:300]
#    - Week 4: companies[300:400], then wrap to 0
#
# 4. LIMIT per run: max 50 companies checked per source per run
#
curated:

  hiring_without_whiteboards:
    name: Hiring Without Whiteboards
    type: curated
    reliability: high
    url: "https://raw.githubusercontent.com/poteto/hiring-without-whiteboards/main/README.md"
    description: |
      Curated list of companies that don't do whiteboard/leetcode interviews.
      Focus on practical, real-world problems instead.
    parse:
      format: markdown
      pattern: |
        - [Company Name](careers_url) | Location(s) | Interview process description
      example: |
        - [Airtable](https://airtable.com/careers) | San Francisco, CA; Remote | Take home project
    workflow: |
      1. Fetch raw README.md from GitHub
      2. Parse markdown list entries
      3. Filter for companies with "Remote" in location
      4. For each matching company:
         - Check if uses Greenhouse/Lever (use API)
         - Otherwise WebSearch "{company} platform engineer remote"
      5. Cross-reference with existing postings to avoid duplicates
    filters:
      location_must_contain:
        - Remote
        - remote
      skip_if_location_contains:
        - Europe only
        - UK only
        - Canada only
    notes: |
      Good for discovering companies with practical interview processes.
      Run weekly (not daily) - list doesn't change frequently.
      Use as company discovery, then check their careers pages.
    schedule: weekly

  awesome_remote_job:
    name: Awesome Remote Job
    type: curated
    reliability: high
    url: "https://raw.githubusercontent.com/lukasz-madon/awesome-remote-job/master/README.md"
    description: |
      200+ companies with "Remote DNA" - fully distributed or remote-first.
      Includes career page links and brief descriptions.
    parse:
      format: markdown
      section: "Companies with Remote DNA"
      pattern: |
        [Company Name](careers_url) - Brief description
      example: |
        [Automattic](https://automattic.com/work-with-us/) - Makers of WordPress.com
        [GitLab](https://about.gitlab.com/jobs/) - Competitor to GitHub
    workflow: |
      1. Fetch raw README.md
      2. Find "Companies with Remote DNA" section
      3. Parse markdown links: [Company](url)
      4. For each company, search for platform/SRE/devops roles
    notes: |
      Comprehensive list of remote-first companies.
      Many are well-known (GitLab, Automattic, Basecamp).
      Run weekly - cross-reference with existing postings.
    schedule: weekly

  four_day_week:
    name: 4 Day Work Week Companies
    type: curated
    reliability: medium
    url: "https://api.github.com/repos/rafaelcamargo/4dayweek/contents/src/companies/data"
    description: |
      Companies with 4-day work weeks. JSON files per company.
      "Full" = year-round, "Partial" = seasonal/restricted.
    parse:
      format: json_directory
      fields:
        name: company name
        adoption: "Full" or "Partial"
        website: main URL
        careers_page: hiring link
        description: how they implement 4-day week
    workflow: |
      1. Fetch directory listing from GitHub API
      2. For each .json file, fetch and parse
      3. Filter for "Full" adoption (skip "Partial")
      4. Check careers_page for platform/SRE roles
    filters:
      adoption: Full  # Skip partial implementations
    notes: |
      Work-life balance focused companies.
      Smaller list but high quality.
      Run monthly - list grows slowly.
    schedule: monthly

# ============================================================
# API SOURCES - Claude can fetch directly, structured responses
# ============================================================
api:

  greenhouse:
    name: Greenhouse Job Boards
    type: api
    reliability: high
    pattern: "https://boards-api.greenhouse.io/v1/boards/{company}/jobs"
    response: json
    notes: |
      Many companies use Greenhouse. Need to know company's board name.
      Returns structured job data including description, location, salary.
    example_companies:
      - discord
      - cloudflare
      - figma
      - notion
      - stripe
    rate_limit: ~100 req/min
    auth: none

  lever:
    name: Lever Job Boards
    type: api
    reliability: high
    pattern: "https://api.lever.co/v0/postings/{company}"
    response: json
    notes: |
      Similar to Greenhouse. Returns job listings with descriptions.
    example_companies:
      - netflix
      - twitch
    rate_limit: unknown
    auth: none

  remoteok:
    name: RemoteOK
    type: api
    reliability: high
    url: "https://remoteok.com/api"
    response: json
    notes: |
      Full job board as JSON. Filter client-side for relevant roles.
      First element is metadata, jobs start at index 1.
    rate_limit: unknown
    auth: none

  ycombinator:
    name: Work at a Startup (YC)
    type: api
    reliability: medium
    url: "https://www.workatastartup.com/api/jobs"
    response: json
    notes: |
      May require parsing. YC-backed companies only.
      Good for startup opportunities.
    auth: none

  hn_whoishiring:
    name: HackerNews Who's Hiring
    type: api
    reliability: high
    pattern: "https://hacker-news.firebaseio.com/v0/item/{thread_id}.json"
    response: json
    notes: |
      Monthly thread, first of each month.
      Get thread ID from HN, then fetch all comments.
      Plain text, need to parse job details from comment body.
    discovery: |
      Search "site:news.ycombinator.com who is hiring {month} {year}"
      to find current thread ID.

# ============================================================
# SEARCH SOURCES - WebSearch discovery, mixed reliability
# ============================================================
search:

  google_jobs:
    name: Google Jobs Search
    type: search
    reliability: medium
    strategy: |
      Build queries dynamically from config.yaml:
      - For each target_role in config.search.target_roles
      - WebSearch: "{role} remote site:boards.greenhouse.io"
      - WebSearch: "{role} remote site:jobs.lever.co"
      Follow links to actual postings.
    notes: |
      Google aggregates from many sources.
      Use site: filters to target scrape-friendly boards.
      Results may be cached/stale.
      Query templates use values from config.yaml at runtime.
    limitations:
      - Snippets only, must fetch full posting
      - May miss recent posts (indexing delay)

  builtin:
    name: Built In
    type: search
    reliability: medium
    url: "https://builtin.com/jobs/remote"
    strategy: |
      WebFetch the search results page.
      May get partial listings.
    limitations:
      - Some JS rendering
      - Pagination tricky

  wellfound:
    name: Wellfound (AngelList)
    type: search
    reliability: low
    url: "https://wellfound.com/jobs"
    strategy: |
      WebSearch: "site:wellfound.com {role} remote"
      (use target_roles from config.yaml)
    limitations:
      - Heavy JS rendering
      - Login prompts
      - Better to use manual

  levels_fyi:
    name: Levels.fyi Jobs
    type: search
    reliability: low
    url: "https://www.levels.fyi/jobs"
    strategy: |
      WebSearch for specific roles.
      Job pages may be accessible.
    limitations:
      - JS heavy
      - Salary data useful but job listings spotty

  company_careers:
    name: Direct Company Career Pages
    type: search
    reliability: varies
    strategy: |
      WebSearch: "{company} careers {role}"
      (use target_roles from config.yaml)
      If on Greenhouse/Lever, use API instead.
      Otherwise WebFetch career page.
    notes: |
      Many companies use ATS that requires JS.
      Check if they use Greenhouse/Lever first (API is better).
    common_ats:
      greenhouse: use api
      lever: use api
      workday: manual (heavy JS)
      icims: manual (heavy JS)
      taleo: manual (legacy, clunky)
      successfactors: manual

# ============================================================
# MANUAL SOURCES - User must browse, Claude processes results
# ============================================================
manual:

  linkedin:
    name: LinkedIn Jobs
    type: manual
    reliability: high (when manual)
    user_actions:
      - Browse linkedin.com/jobs with your filters
      - Save interesting jobs to a list
      - Copy job URL + description to Claude
      - Or export saved jobs if LinkedIn allows
    why_manual: |
      - Login required
      - Heavy bot detection (999 errors)
      - Best job data but inaccessible to automation
      - Easy Apply requires your session
    integration: |
      When you find a job, tell Claude:
      "Add this LinkedIn job: {paste URL and description}"
      Claude creates the posting.yaml from your input.

  indeed:
    name: Indeed
    type: manual
    reliability: high (when manual)
    user_actions:
      - Search indeed.com with filters
      - Copy job details to Claude
    why_manual: |
      - Aggressive bot detection
      - Captchas
      - Dynamic content
    integration: |
      Paste job posting text to Claude for processing.

  glassdoor:
    name: Glassdoor
    type: manual
    reliability: medium
    user_actions:
      - Browse for jobs
      - Note company ratings/reviews
      - Copy job details
    why_manual: |
      - Login walls
      - Limited views without account
    useful_for: |
      Company research, salary data, interview questions.
      Not primary job discovery.

  otta:
    name: Otta
    type: manual
    reliability: medium
    user_actions:
      - Browse otta.com (requires account)
      - Swipe on jobs
      - Copy interesting ones to Claude
    why_manual: |
      - Account required
      - Personalized feed based on profile

  referrals:
    name: Referral Requests
    type: manual
    user_actions:
      - Check referral_candidates in pending postings
      - Message connections on LinkedIn
      - Track referral status in posting events
    why_manual: |
      - Requires your personal outreach
      - LinkedIn messaging
    integration: |
      After reaching out, add event:
      type: note
      data:
        content: "Messaged {name} for referral, awaiting response"

  email_alerts:
    name: Job Alert Emails
    type: manual
    reliability: high
    setup:
      linkedin: |
        1. Set up job alerts on LinkedIn
        2. Forward alert emails to yourself
        3. Paste relevant jobs to Claude
      indeed: |
        1. Create Indeed job alerts
        2. Review daily digest
        3. Paste relevant jobs to Claude
    integration: |
      Most reliable way to get LinkedIn/Indeed jobs
      without bot detection. Forward emails or paste content.

  connections_export:
    name: LinkedIn Connections Export
    type: manual
    frequency: monthly
    user_actions:
      - LinkedIn Settings → Data Privacy → Get a copy of your data
      - Select "Connections"
      - Download and save as connections.csv
    integration: |
      Place in repo root. Agent uses for referral matching.
      Re-export monthly to capture new connections.

# ============================================================
# AGENT WORKFLOW
# ============================================================
workflow:

  daily_autonomous:
    description: What Claude does at 5am without user
    sources:
      - rss.weworkremotely (programming, devops, product feeds)
      - api.greenhouse (check known companies)
      - api.lever (check known companies)
      - api.remoteok (full scan)
      - api.hn_whoishiring (if new thread)
      - search.google_jobs (discovery)
      - curated.hiring_without_whiteboards (weekly - check if Monday)
    actions:
      - Fetch RSS feeds first (most reliable, structured)
      - Health check existing postings (URLs may fail, log don't assume)
      - Fetch from API sources
      - Search for new postings
      - On Mondays: scan Hiring Without Whiteboards for new remote companies
      - Create posting.yaml for qualifying jobs
      - Update tracker

  hourly_monitor:
    description: What Claude does every 2 hours (6am-8pm) for fresh jobs
    sources:
      - rss.weworkremotely (check pubDate for <12hr old posts)
      - api.remoteok (check date field)
    actions:
      - Fetch RSS/API sources
      - Filter to jobs posted within last 12 hours
      - Skip jobs already in postings/
      - Send instant email alert for fresh matches
      - Create posting.yaml for qualifying jobs

  user_session:
    description: When user is actively working with Claude
    sources:
      - manual.linkedin (user browses, pastes to Claude)
      - manual.indeed (user browses, pastes to Claude)
      - manual.referrals (user messages connections)
    actions:
      - Process job descriptions user provides
      - Create posting.yaml from pasted content
      - Analyze match rate
      - Suggest referral candidates
      - Help draft outreach messages

  weekly_maintenance:
    description: User tasks to do weekly
    tasks:
      - Review .review flagged folders
      - Browse LinkedIn/Indeed for 15 min, paste good finds
      - Check email alerts
      - Update any stale postings
      - Re-export connections.csv if needed

# ============================================================
# KNOWN COMPANIES (for API sources)
# ============================================================
# Companies known to use Greenhouse/Lever APIs
# Agent should check these directly

greenhouse_companies:
  - airbnb
  - asana
  - cloudflare
  - coinbase
  - datadog
  - discord
  - dropbox
  - figma
  - gitlab
  - hashicorp
  - hubspot
  - instacart
  - lattice
  - mongodb
  - notion
  - okta
  - pagerduty
  - plaid
  - reddit
  - segment
  - sentry
  - slack
  - snyk
  - splunk
  - square
  - stripe
  - twilio
  - vercel
  - webflow
  - zapier

lever_companies:
  - palantir
  # - netflix    # Empty as of 2026-01
  # - twitch     # 404 as of 2026-01, moved off Lever
